// <auto-generated />
using CloudeDemmo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudeDemmo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220416132426_SeedAlgoProjectsTable")]
    partial class SeedAlgoProjectsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudeDemmo.Models.AlgoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AlgoProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Item1",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Item2",
                            LongDescription = "It's a longdescription",
                            Owner = "User2",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "DANN",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "AjaxTest",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        });
                });

            modelBuilder.Entity("CloudeDemmo.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });
#pragma warning restore 612, 618
        }
    }
}
