// <auto-generated />
using CloudeDemmo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudeDemmo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudeDemmo.Models.AlgoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AlgoProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemName = "Item1",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 2,
                            ItemName = "Item2",
                            LongDescription = "It's a longdescription",
                            Owner = "User2",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 3,
                            ItemName = "DANN",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        },
                        new
                        {
                            Id = 4,
                            ItemName = "AjaxTest",
                            LongDescription = "It's a longdescription",
                            Owner = "User1",
                            ShortDescription = "It's shortdescription"
                        });
                });

            modelBuilder.Entity("CloudeDemmo.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Datasets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataName = "西储数据集",
                            LongDescription = "无",
                            Owner = "用户1",
                            ShortDescription = "凯斯西储大学轴承故障数据"
                        },
                        new
                        {
                            Id = 2,
                            DataName = "数据2",
                            LongDescription = "无",
                            Owner = "用户1",
                            ShortDescription = "测试"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
